name: "@internal/lorem-ipsum-docker"
version: 1.0.0
main: dist/index.js

# license, none for the example
license: UNLICENSED

# scripts comment
scripts:
  start: node dist/index.js
  build: tsc
  test: vitest src
  dev: ts-node ./src/index.ts

dependencies:
  "@internal/phrase-lorem-ipsum": "workspace:*"
  typescript: ^5.3.3

devDependencies:
  "@types/node": ^20.11.17
  ts-node: ^10.9.2
  vitest: ^3.2.4

# plugin stuff
yarn.build:
  input: .
  output: dist
