plugins:
  - path: .yarn/plugins/@ojkelly/plugin-package-yaml.cjs
    spec: "https://yarn.build/yaml"
  - path: .yarn/plugins/@ojkelly/plugin-build.cjs
    spec: "https://yarn.build/latest"

yarnPath: .yarn/releases/yarn-3.0.0-rc.12.cjs
# yarnPath: .yarn/releases/yarn.js
