plugins:
  - path: .yarn/plugins/@ojkelly/plugin-package-yaml.cjs
    spec: "https://yarn.build/yaml"
  - path: .yarn/plugins/@ojkelly/plugin-all.cjs
    spec: "https://yarn.build/latest"

yarnPath: .yarn/releases/yarn-3.2.0.cjs

packageExtensions:
  "@jest/core@*":
    dependencies:
      "ts-node": "*"
  "@cspotcode/source-map-support@*":
    dependencies:
      "source-map-support": "*"
